# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='owner',
        ),
        migrations.AddField(
            model_name='shoe',
            name='owners',
            field=models.ManyToManyField(related_name='shoes', to='relate.Person'),
        ),
    ]
